#!/bin/bash
# Export pixi environment to environment.yml for Binder compatibility

set -e

# Export environment
pixi workspace export conda-environment environment.yml

# Add warning header
{
    echo "# AUTO-GENERATED - DO NOT EDIT"
    echo "# This file is automatically generated from pyproject.toml by pre-commit."
    echo "# To update dependencies, edit pyproject.toml and run: pixi workspace export conda-environment environment.yml"
    cat environment.yml
} > environment.yml.tmp && mv environment.yml.tmp environment.yml

# Stage the updated file if it changed
if ! git diff --quiet environment.yml 2>/dev/null; then
    git add environment.yml
fi
